"""'6'

Revision ID: 888875d18551
Revises: dfdc3d411101
Create Date: 2018-03-27 16:30:53.276000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888875d18551'
down_revision = 'dfdc3d411101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_votes'), 'answers', ['votes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_votes'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
