"""'4'

Revision ID: d1fc9a574ac9
Revises: 38e637db272b
Create Date: 2018-03-27 11:20:22.135000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fc9a574ac9'
down_revision = '38e637db272b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.add_column(u'users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column(u'users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('profession', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'profession')
    op.drop_column(u'users', 'location')
    op.drop_column(u'users', 'about_me')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
