"""'5'

Revision ID: dfdc3d411101
Revises: d1fc9a574ac9
Create Date: 2018-03-27 15:58:38.771000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdc3d411101'
down_revision = 'd1fc9a574ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'desc')
    # ### end Alembic commands ###
